server:
  port: 8585

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-store?createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

